name: Main Workflow
on: [push, workflow_dispatch]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci
      - name: Lint
        run: npm run lint
